#!/bin/bash

# Written by Mauricio Pamplona Segundo for Program Design
# try_project4_inventory is a Unix shell script that will be used to test project 4.
# To use the script, copy it into the same directory as your scource file
# Set execute permission for the file by issuing the command:
# chmod +x try_project4_inventory
# Compile your program, producing a.out as the executable
# To run the script, type 
# ./try_project4_inventory
# The user input from the script will not be shown on the screen.
# Compare the results from your program with the expected results on the test cases.
echo '===================================================='
./a.out <<-EndOfInput
10 2
1 1 1 1 1 2 2 2 2 2
EndOfInput
echo '----------------------------------------------------'
echo 'Expected:'
echo 'Enter number of parts (N): 10'
echo 'Enter number of part types (K): 2'
echo 'Enter part list:'
echo '1 1 1 1 1 2 2 2 2 2'
echo 'The factory can build 5 computer(s).'
echo '===================================================='
./a.out <<-EndOfInput
20 5
1 2 3 4 1 2 3 4 1 2 3 4 5 1 2 3 4 5 4 4
EndOfInput
echo '----------------------------------------------------'
echo 'Expected:'
echo 'Enter number of parts (N): 20'
echo 'Enter number of part types (K): 5'
echo 'Enter part list:'
echo '1 2 3 4 1 2 3 4 1 2 3 4 5 1 2 3 4 5 4 4'
echo 'The factory can build 2 computer(s).'
echo '===================================================='
./a.out <<-EndOfInput
3 1
1 1 1
EndOfInput
echo '----------------------------------------------------'
echo 'Expected:'
echo 'Enter number of parts (N): 3'
echo 'Enter number of part types (K): 1'
echo 'Enter part list:'
echo '1 1 1'
echo 'The factory can build 3 computer(s).'
echo '===================================================='
./a.out <<-EndOfInput
39 11
3 8 7 11 2 8 1 1 5 11 1 1 10 9 2 10 5 3 1 1 3 11 8 1 1 4 4 8 8 5 3 11 4 4 7 4 9 3 2
EndOfInput
echo '----------------------------------------------------'
echo 'Expected:'
echo 'Enter number of parts (N): 39'
echo 'Enter number of part types (K): 11'
echo 'Enter part list:'
echo '3 8 7 11 2 8 1 1 5 11 1 1 10 9 2 10 5 3 1 1 3 11 8 1 1 4 4 8 8 5 3 11 4 4 7 4 9 3 2'
echo 'The factory can build 0 computer(s).'
echo '===================================================='
./a.out <<-EndOfInput
49 22
5 18 7 15 14 15 16 14 13 19 18 13 10 3 20 2 12 17 14 12 10 4 4 19 11 12 12 9 22 2 16 13 5 1 6 13 21 16 2 7 13 11 20 22 19 8 6 1 20
EndOfInput
echo '----------------------------------------------------'
echo 'Expected:'
echo 'Enter number of parts (N): 49'
echo 'Enter number of part types (K): 22'
echo 'Enter part list:'
echo '5 18 7 15 14 15 16 14 13 19 18 13 10 3 20 2 12 17 14 12 10 4 4 19 11 12 12 9 22 2 16 13 5 1 6 13 21 16 2 7 13 11 20 22 19 8 6 1 20'
echo 'The factory can build 1 computer(s).'
echo '===================================================='
./a.out <<-EndOfInput
0
EndOfInput
echo '----------------------------------------------------'
echo 'Expected:'
echo 'Enter number of parts (N): 0'
echo 'Invalid number of parts 0'
echo 'Must be in the range [1,1000000]'
echo '===================================================='
./a.out <<-EndOfInput
1000001
EndOfInput
echo '----------------------------------------------------'
echo 'Expected:'
echo 'Enter number of parts (N): 1000001'
echo 'Invalid number of parts 1000001'
echo 'Must be in the range [1,1000000]'
echo '===================================================='
./a.out <<-EndOfInput
1 0
EndOfInput
echo '----------------------------------------------------'
echo 'Expected:'
echo 'Enter number of parts (N): 1'
echo 'Enter number of part types (K): 0'
echo 'Invalid number of part types 0'
echo 'Must be in the range [1,10000]'
echo '===================================================='
./a.out <<-EndOfInput
1 10001
EndOfInput
echo '----------------------------------------------------'
echo 'Expected:'
echo 'Enter number of parts (N): 1'
echo 'Enter number of part types (K): 10001'
echo 'Invalid number of part types 10001'
echo 'Must be in the range [1,10000]'
echo '===================================================='
./a.out <<-EndOfInput
3 2
0
EndOfInput
echo '----------------------------------------------------'
echo 'Expected:'
echo 'Enter number of parts (N): 3'
echo 'Enter number of part types (K): 2'
echo 'Enter part list:'
echo '0'
echo 'Invalid list of parts'
echo 'Part codes must be in the range [1,2]'
echo '----------------------------------------------------'



