#!/bin/bash

# Written by Mauricio Pamplona Segundo for Program Design
# try_project3_cities is a Unix shell script that will be used to test project 3.
# To use the script, copy it into the same directory as your scource file
# Set execute permission for the file by issuing the command:
# chmod +x try_project3_cities
# Compile your program, producing a.out as the executable
# To run the script, type 
# ./try_project3_cities
# The user input from the script will not be shown on the screen.
# Compare the results from your program with the expected results on the test cases.
echo '===================================================='
./a.out <<-EndOfInput
5 2
3 2
4 4
EndOfInput
echo '----------------------------------------------------'
echo 'Expected:'
echo 'Enter number of cities (N): 5'
echo 'Enter number of drones (M): 2'
echo 'Enter drone list:'
echo '3 2'
echo '4 4'
echo 'Cities reached by a drone:'
echo '1 3 4 5'
echo '===================================================='
./a.out <<-EndOfInput
8 3
3 3
2 2
6 2
EndOfInput
echo '----------------------------------------------------'
echo 'Expected:'
echo 'Enter number of cities (N): 8'
echo 'Enter number of drones (M): 3'
echo 'Enter drone list:'
echo '3 3'
echo '2 2'
echo '6 2'
echo 'Cities reached by a drone:'
echo '2 3 4 6 8'
echo '===================================================='
./a.out <<-EndOfInput
4 1
1 1
EndOfInput
echo '----------------------------------------------------'
echo 'Expected:'
echo 'Enter number of cities (N): 4'
echo 'Enter number of drones (M): 1'
echo 'Enter drone list:'
echo '1 1'
echo 'Cities reached by a drone:'
echo '1 2 3 4'
echo '===================================================='
./a.out <<-EndOfInput
39 16
27 26
34 37
36 33
17 25
38 39
29 14
9 35
34 14
13 36
16 11
11 2
35 11
27 36
20 29
34 39
3 24
EndOfInput
echo '----------------------------------------------------'
echo 'Expected:'
echo 'Enter number of cities (N): 39'
echo 'Enter number of drones (M): 16'
echo 'Enter drone list:'
echo '27 26'
echo '34 37'
echo '36 33'
echo '17 25'
echo '38 39'
echo '29 14'
echo '9 35'
echo '34 14'
echo '13 36'
echo '16 11'
echo '11 2'
echo '35 11'
echo '27 36'
echo '20 29'
echo '34 39'
echo '3 24'
echo 'Cities reached by a drone:'
echo '1 2 3 5 6 7 9 11 13 15 16 17 19 20 21 23 24 25 27 29 31 33 34 35 36 37 38 39'
echo '===================================================='
./a.out <<-EndOfInput
0
EndOfInput
echo '----------------------------------------------------'
echo 'Expected:'
echo 'Enter number of cities (N): 0'
echo 'Invalid number of cities 0'
echo 'Must be in the range [1,100]'
echo '===================================================='
./a.out <<-EndOfInput
4 101
EndOfInput
echo '----------------------------------------------------'
echo 'Expected:'
echo 'Enter number of cities (N): 4'
echo 'Enter number of drones (M): 101'
echo 'Invalid number of drones 101'
echo 'Must be in the range [1,100]'
echo '===================================================='
./a.out <<-EndOfInput
4 3
0 1
EndOfInput
echo '----------------------------------------------------'
echo 'Expected:'
echo 'Enter number of cities (N): 4'
echo 'Enter number of drones (M): 3'
echo 'Enter drone list:'
echo '0 1'
echo 'Invalid list of drones'
echo 'Drone location and travel distance must be in the range [1,4]'
echo '===================================================='
./a.out <<-EndOfInput
4 3
1 5
EndOfInput
echo '----------------------------------------------------'
echo 'Expected:'
echo 'Enter number of cities (N): 4'
echo 'Enter number of drones (M): 3'
echo 'Enter drone list:'
echo '1 5'
echo 'Invalid list of drones'
echo 'Drone location and travel distance must be in the range [1,4]'
echo '----------------------------------------------------'



